# Generated by Django 4.0 on 2021-12-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('G', 'G'), ('M', 'M')], max_length=1)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='DOB')),
                ('phone', models.CharField(blank=True, help_text='Home/Work Phone', max_length=10)),
                ('phone1', models.CharField(blank=True, max_length=10, verbose_name='mobile')),
                ('nic', models.CharField(blank=True, max_length=6, verbose_name='NIC')),
            ],
        ),
    ]
