# Generated by Django 4.0 on 2021-12-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
