# Generated by Django 4.0 on 2021-12-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1),
        ),
    ]
